AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Daily 6 a.m. Eastern scheduler
  --------------------------------
  A Lambda function that runs every day at 6 a.m. America/New_York
  (EventBridge Scheduler handles daylight-saving time automatically).

Globals:
  Function:
    Timeout: 60
    LoggingConfig:
      LogFormat: JSON          # structured logs in CloudWatch

Resources:
  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scheduler_function/      # your source folder
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures: [x86_64]

      # ── EventBridge Scheduler trigger ────────────────────────────────────────
      Events:
        DailyTrigger:
          Type: ScheduleV2                 # SAM wrapper for AWS::Scheduler::Schedule
          Properties:
            ScheduleExpression: "cron(0 6 * * ? *)"          # 6:00 every day
            ScheduleExpressionTimezone: "America/New_York"   # evaluate in Eastern Time
            FlexibleTimeWindow:
              Mode: "OFF"                                   # fire exactly at 6:00

Outputs:
  LambdaArn:
    Description: Scheduler Lambda Function ARN
    Value: !GetAtt SchedulerFunction.Arn
  FunctionName:
    Description: Lambda function name
    Value: !Ref SchedulerFunction
